import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['index'],
    },
    {
      type: 'category',
      label: 'Setup Guides',
      collapsible: false,
      items: [
        'digital-twin-workstation',
        'physical-ai-edge-kit',
        'cloud-native-development',
      ],
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2',
      collapsible: true,
      items: [
        'chapter1-introduction-to-ros2',
        'chapter2-nodes-topics',
        'chapter3-services-actions-parameters',
        'chapter4-urdf-robot-modeling',
        'chapter5-launch-files-package-management',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin',
      collapsible: true,
      items: ['module-2-digital-twin'],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac',
      collapsible: true,
      items: ['module-3-nvidia-isaac'],
    },
    {
      type: 'category',
      label: 'Module 4: VLA & Humanoids',
      collapsible: true,
      items: ['module-4-vla-models'],
    },
    {
      type: 'category',
      label: 'Appendices',
      items: ['references', 'robotics-glossary'],
    },
  ],
};

export default sidebars;
